Rocm support
iotamudelta/faiss pull request #3
Opened 2024-05-10 21:42 UTC by ItsPitt

2024-05-10 21:44 UTC, ItsPitt commented
Not sure why it's chowing all of those commits. It was only for the last one.

2024-05-13 13:08 UTC, iotamudelta requested changes
the actual change in IVFFlat LGTM. please revert the white space only changes in the other two files

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/impl/PQCodeLoad.cuh
> +    using T = uint8_t __attribute__((ext_vector_type(3)));
can you revert the white space change?

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/impl/PQCodeLoad.cuh
> +    using T = uint32_t __attribute__((ext_vector_type(3)));
same here

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/impl/PQCodeLoad.cuh
> +    using T = uint32_t __attribute__((ext_vector_type(4)));
and here

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/impl/PQCodeLoad.cuh
> +    using T = uint32_t __attribute__((ext_vector_type(5)));
and here

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/impl/PQCodeLoad.cuh
> +    using T = uint32_t __attribute__((ext_vector_type(6)));
and here

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/impl/PQCodeLoad.cuh
> +    T* t = reinterpret_cast<T*>(p);
here

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/impl/PQCodeLoad.cuh
> +    u[0] = __builtin_nontemporal_load(t);
here

2024-05-13 13:08 UTC, iotamudelta commented on faiss/gpu/utils/LoadStoreOperators.cuh
> +        Half8* t = reinterpret_cast<Half8*>(p);
here

2024-05-13 13:27 UTC, iotamudelta commented
> Not sure why it's showing all of those commits. It was only for the last one.

and I'll just squash and merge - so the extra commits will go away

2024-05-13 15:36 UTC, ItsPitt commented
Those white space changes were done because the code I pulled over from the other branch had tabs in those spots. While the rest of the file had spaces. I shared those to match the rest of the file.

2024-05-13 18:05 UTC, merged